# A simple name for your workflow
name: Website Health Check

# Controls when the action will run
on:
  # This schedule runs the workflow every 30 minutes
  schedule:
    - cron: '*/30 * * * *'
  # Allows you to run this workflow manually from the Actions tab on GitHub
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "health-check"
  health-check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks the status of your live website
      - name: Check website status
        run: |
          # Uses curl to make a request to your site.
          # -s: silent mode
          # -o /dev/null: discards the response body
          # -w "%{http_code}": outputs only the HTTP status code
          # The grep command checks if the status code is 200 (OK).
          # If it's not 200, the grep command will fail, causing the workflow to fail and notify you.
          curl -s -o /dev/null -w "%{http_code}" https://galacticarchives.space | grep 200 || exit 1
